version: "3"
services:
  server:
    build: ./server
    command: "bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./server:/app/server
    ports:
      - "3020:3000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: server_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  client:
    build: ./client
    command: "npm run start"
    volumes:
      - ./client:/app/client
    ports:
      - "4020:3000"
volumes:
  server_db: